name: Build NUC980 image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * MON'

concurrency:
  group: nuc980-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Buildroot Build
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
#      - uses: docker/login-action@v2
#        name: Login to Github Container Registry
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: crazy-max/ghaction-github-runtime@v1 # This is required to enable gha cache layers.
      - name: Build
        run: docker compose build
