name: Build NUC980 image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * MON'

concurrency:
  group: nuc980-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Buildroot Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - nuvoton_nuc980_defconfig
          - nuvoton_nuc980_iot_defconfig
          - nuvoton_nuc980_iot_g2_defconfig
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: crazy-max/ghaction-github-runtime@v1 # This is required to enable gha cache layers.
      - name: Build ${{ matrix.config }}
        run: docker build -t nuc980:${{ matrix.config }} --build-arg="CONFIG=${{ matrix.config }}" --progress plain .
      - name: Extract build artifacts
        run: |
          docker cp nuc980:${{ matrix.config }}:/buildroot-docker/buildroot/uImage ./artifacts/uImage
          docker cp nuc980:${{ matrix.config }}:/buildroot-docker/buildroot/rootfs.cpio ./artifacts/rootfs.cpio
          docker cp nuc980:${{ matrix.config }}:/buildroot-docker/buildroot/rootfs.tar ./artifacts/rootfs.tar
          docker cp nuc980:${{ matrix.config }}:/buildroot-docker/buildroot/u-boot.bin ./artifacts/u-boot.bin
          docker cp nuc980:${{ matrix.config }}:/buildroot-docker/buildroot/output/build/image/980image ./artifacts/980image
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config }}
          path: |
            ./artifacts/*
